// SPDX-License-Identifier: PMPL-1.0-or-later
// GENERATED by language-interop-compiler
// Source: examples/user-type.idr
// Target: ReScript
// Compatibility: Concorde (100% fidelity with Rust)

// Type definition (matches Idris2 abstract IR)
type user = {
  id: int,
  name: string,
  email: string,
  active: bool,
}

// Validation function (translated from Idris2)
let validateUser = (u: user): result<user, string> => {
  if u.name == "" {
    Error("Name is required")
  } else if u.email == "" {
    Error("Email is required")
  } else {
    Ok(u)
  }
}

// Example usage
let exampleUser: user = {
  id: 1,
  name: "Alice",
  email: "alice@example.com",
  active: true,
}

// FFI binding to Rust implementation (zero-copy, proven safe)
@module("./user_ffi")
external validateUserRust: user => result<user, string> = "validate_user"

// Type-safe interop: ReScript calls Rust
let validateWithRust = (u: user) => validateUserRust(u)
